openapi: "3.0.0"
info:
  description: "This is a daifuku api stub. "
  version: "1.0.0"
  title: "Daifuiku Api Stub"
  contact:
    email: "fukushima9952@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
- name: "messages"
  description: "Operations about today's messages"
  externalDocs:
    description: "make random messages"
    url: "https://github.com/daifuku99/DaifukuProject/tree/master/daifuku_server"
servers:
  - url: http://localhost:8001/api/v1
    description: Daifuku server
paths:
  # paths
  /messages:
    get:
      tags:
        - messages
      summary: get today messages
      description: Returns an array of Today messsages
      parameters: []
      responses:
        '200':
          description: A json array of todays messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Messages'
                example:
                  messagesList:
                    - messageId: '1'
                      messageName: 'NyaoNyao'
                      form:
                        formName: 'aaa'
                        formId: '1'
    post:
      tags:
        - messages
      summary: Create a new messages
      description: Create a new messages
      parameters: []
      requestBody:
        description: messages to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Messages'
            example:
              messageId: '99'
              messageName: 'Create Test'
              form:
                formName: 'create test'
                formId: '1'
      responses:
        '201':
          description: Complete to create Message
components:
  schemas:
    Messages:
      type: object
      required:
        - messageId
      properties:
        messageId:
            type: integer
            format: int64
        messageName:
            type: string
